### ISSUE TITLE
update unnitest with new changes

### ISSUE THREAD

**Issue by horaciobam** [PoonLab/HexSE#121]

**Comment by ArtPoon** [comment]
* run existing unit test suite
* identify gaps in coverage

**Comment by SandeepThokala** [comment]
tests/test_run_simulation.py 84% coverage.
`NameError: name 'get_open_reading_frames' is not defined`
testBackToBackORFs1, testBackToBackORFs2, testBackToBackORFs3, testBackToBackORFs4, testInternalORF, testLowerCaseInput, testMultipleORFs, testNoStartNoStop, testOneORF, testOnlyStartCodon, testOnlyStopCodon, testSimpleUse2, testSimpleUse3, testStopBeforeStart, testTwoStartSameFrame

`NameError: name 'stop_in_seq' is not defined`
test_internal_stop, test_stop_out_of_frame

`TypeError: count_internal_stop_codons() takes 1 positional argument but 3 were given`
test_internal_stop_codon, test_no_internal_stop_codons

`NameError: name 'parse_genbank_orfs' is not defined`
test_genbank_format

`TypeError: Settings.parse_orfs_from_yaml() missing 1 required positional argument: 'yaml'`
test_yaml_format

`AssertionError:`
test_create_mu_dict, test_create_omega_dict, testCorrectInput, testMultipleNotOrfs, testNotMultipleOfThree, testOutsideRangeOfSequence

**Comment by SandeepThokala** [comment]
test/test_sequence_info.py 14% coverage
`KeyError: 'orf_map'`
caused failure of all the tests

**Comment by SandeepThokala** [comment]
test/test_simulation.py 19% coverage
`KeyError: 'orf_map'`
caused failure of all the tests

**Comment by ArtPoon** [comment]
Close this issue, and open new issues for each script that requires improved coverage
