### ISSUE TITLE
Overlapping regions accumulating more mutations than single ORF region  

### ISSUE THREAD

**Issue by horaciobam** [PoonLab/HexSE#122]

**Comment by horaciobam** [comment]
Error in calculation of `coords` and `len` in `all_maps` for overlapping reading frames on spliced genes. 
Tuple `(0,0,1,1)` should have `coords: [[2849,3182], [0,837]]` and `len: 1199` . Same error for `len` and `coords` of non-overlapping CDSs from spliced genes. 


```python
All Maps
{ (0, 0, 1, 0): {'coords': [[837, 2848]], 'len': 2012},
  (0, 0, 1, 1): {'coords': [[0, 3181]], 'len': 3182},
  (0, 1, 0, 0): {'coords': [[1840, 2307]], 'len': 468},
  (0, 1, 1, 0): {'coords': [[2308, 2453]], 'len': 146},
  (1, 0, 0, 0): {'coords': [[1625, 1814]], 'len': 190},
  (1, 0, 1, 0): {'coords': [[1375, 1624]], 'len': 250},
  (1, 1, 0, 0): {'coords': [[1815, 1839]], 'len': 25}}

ORFS
{ '+0': [ { 'coords': [[1375, 1840]],
            'omega_classes': 5,
            'omega_shape': 1.0,
            'omega_values': [ 0.04297031789726438,
                              0.1440389335835469,
                              0.27995816301986465,
                              0.4892574205256841,
                              1.04377516497364],
            'orf_map': array([1, 0, 0, 0])},
          { 'coords': [[2308, 3182], [0, 1625]],
            'omega_classes': 2,
            'omega_shape': 1.2,
            'omega_values': [0.1691149716766538, 0.7908850282996809],
            'orf_map': array([0, 0, 1, 0])}],
  '+1': [ { 'coords': [[2849, 3182], [0, 837]],
            'omega_classes': 3,
            'omega_shape': 1.2,
            'omega_values': [ 0.11098924219663184,
                              0.36293140817456776,
                              0.9660793495713997],
            'orf_map': array([0, 0, 0, 1])}],
  '+2': [ { 'coords': [[1815, 2454]],
            'omega_classes': 4,
            'omega_shape': 1.0,
            'omega_values': [ 0.05478151305786287,
                              0.190700742494181,
                              0.3999999999999998,
                              0.9545177444479566],
            'orf_map': array([0, 1, 0, 0])}],
  '-0': [],
  '-1': [],
  '-2': []}
```

**Comment by horaciobam** [comment]
Trying to understand why some regions mute more than others. 

![image](https://user-images.githubusercontent.com/42696510/192561194-59e146d7-a645-4644-972c-e8caec1be451.png)

**Is it related to the way we select a specific region to mutate?** (Selection of regions is based on the number of nucleotides associated with it). 

```python
>>> Binary codes (combos) and their coordinates on the genome
all_maps = {(0, 0, 1, 0): {'coords': [[837, 1374], [2454, 2848]], 'len': 933},
            (0, 0, 1, 1): {'coords': [[0, 836], [2849, 3181]], 'len': 1170},
            (0, 1, 0, 0): {'coords': [[1840, 2307]], 'len': 468},
            (0, 1, 1, 0): {'coords': [[2308, 2453]], 'len': 146},
            (1, 0, 0, 0): {'coords': [[1625, 1814]], 'len': 190},
            (1, 0, 1, 0): {'coords': [[1375, 1624]], 'len': 250},
            (1, 1, 0, 0): {'coords': [[1815, 1839]], 'len': 25}}
```

In the `dict` from which we are selecting a given region, longer regions have a higher probability of being selected:
```python
>>> Region probability
orf_dict = { (0, 0, 1, 0): 75.64864864864866,
            (0, 0, 1, 1): 88.98177247014456,
            (0, 1, 0, 0): 15.148962916404777,
            (0, 1, 1, 0): 1.6517913262099309,
            (1, 0, 0, 0): 3.164676304211188,
            (1, 0, 1, 0): 2.042740414833438,
            (1, 1, 0, 0): 0.023570081709616594}
```

When we select the region, we consider the number of events on that branch of the `event_tree`:
https://github.com/PoonLab/HexSE/blob/f57ea16a80cff18e0122efaff3b4a21b5e949b3b/hexse/simulation.py#L80-L91

The only problem I notice so far is that region `(1, 1, 0, 0)` is rarely selected since it is so small (its probability is very low). Other than that, region selection seems to be working as planed. 


**Is it related with the selection of omegas?**

Next we selected the combination of omegas from a dictionary that relates each omega combination with its probability. If region `(0, 0, 1, 1)` is selected, the selection of `omega` would be based on:
```python
{ (None, None, -1, -1): 12,
  (None, None, -1, 0): 6.996244283233251,
  (None, None, -1, 1): 38.60375571676675,
  (None, None, 0, -1): 6.505279772129163,
  (None, None, 0, 0): 0.27117692005913546,
  (None, None, 0, 1): 1.7456778732348441,
  (None, None, 1, -1): 34.54020248342288,
  (None, None, 1, 0): 2.7432080865118977,
  (None, None, 1, 1): 9.632271180127988}
```

I think the problem is that we are selecting a region **BEFORE** considering its coding context. So even if I use the same parameters for all `orfs`, larger regions will be selected more often than smaller ones, making overlapping and non-overalapping regions look like they accumulate a similar amount of mutations.

![image](https://user-images.githubusercontent.com/42696510/192570024-9fb9384b-36fa-4533-94a3-8ce1c3e09cea.png)

@ArtPoon should we include information about the coding context (e.g. multiple for all `omegas` in the region) when selecting a region, modifying the region probability?

**Comment by horaciobam** [comment]
I tried to multiply each region by the values of all omegas combinations on it. Now effect of the overlap is notorious but the probability gets too small:

```python
 ORF dict for orf combo:  (0, 0, 1, 1)
{(0, 0, 1, 1): 3.7611119029372136e-05}

 ORF dict for orf combo:  (0, 0, 1, 0)
{(0, 0, 1, 0): 4.752924244515001, (0, 0, 1, 1): 3.7611119029372136e-05}

 ORF dict for orf combo:  (1, 0, 1, 0)
{ (0, 0, 1, 0): 4.752924244515001,
  (0, 0, 1, 1): 3.7611119029372136e-05,
  (1, 0, 1, 0): 2.307271569902207e-06}

 ORF dict for orf combo:  (1, 0, 0, 0)
{ (0, 0, 1, 0): 4.752924244515001,
  (0, 0, 1, 1): 3.7611119029372136e-05,
  (1, 0, 0, 0): 0.1935810517594534,
  (1, 0, 1, 0): 2.307271569902207e-06}

 ORF dict for orf combo:  (1, 1, 0, 0)
{ (0, 0, 1, 0): 4.752924244515001,
  (0, 0, 1, 1): 3.7611119029372136e-05,
  (1, 0, 0, 0): 0.1935810517594534,
  (1, 0, 1, 0): 2.307271569902207e-06,
  (1, 1, 0, 0): 0.003096259762448625}

 ORF dict for orf combo:  (0, 1, 0, 0)
{ (0, 0, 1, 0): 4.752924244515001,
  (0, 0, 1, 1): 3.7611119029372136e-05,
  (0, 1, 0, 0): 1.2837480274574278,
  (1, 0, 0, 0): 0.1935810517594534,
  (1, 0, 1, 0): 2.307271569902207e-06,
  (1, 1, 0, 0): 0.003096259762448625}

 ORF dict for orf combo:  (0, 1, 1, 0)
{ (0, 0, 1, 0): 4.752924244515001,
  (0, 0, 1, 1): 3.7611119029372136e-05,
  (0, 1, 0, 0): 1.2837480274574278,
  (0, 1, 1, 0): 5.601744278926615e-07,
  (1, 0, 0, 0): 0.1935810517594534,
  (1, 0, 1, 0): 2.307271569902207e-06,
  (1, 1, 0, 0): 0.003096259762448625}

 ORF dict for orf combo:  nt_events
{ (0, 0, 1, 0): 4.752924244515001,
  (0, 0, 1, 1): 3.7611119029372136e-05,
  (0, 1, 0, 0): 1.2837480274574278,
  (0, 1, 1, 0): 5.601744278926615e-07,
  (1, 0, 0, 0): 0.1935810517594534,
  (1, 0, 1, 0): 2.307271569902207e-06,
  (1, 1, 0, 0): 0.003096259762448625}
Selected combo: (0, 0, 1, 0)
```
So of course, regions with overlaps never mutate. 

![image](https://user-images.githubusercontent.com/42696510/192582449-05d10df8-c875-4d02-a5d5-289f56cf0c5e.png)

I will try multiplying each the value of each `omega_combo` by the number of nucleotides under those omegas.

**Comment by ArtPoon** [comment]
Okay I think we should be calculating the probability of selecting a genome region by the number of substitution events (leaf nodes) stored under that node.

**Comment by ArtPoon** [comment]
I think we *have* to select the genome region before coding context (type of substitution wrt. dN/dS) because the context is determined by the genome region.

**Comment by horaciobam** [comment]
The problem is that we are not considering the coding context when selecting the region.

I think that the selection of the region should include information on the seleciton pressures. For example, I did this:

```python
value_omegas_in_region = 0  # sum of all omega combinations on the region by the number of nucleotides with such combination
                            for omega_combo in branch[cat][orf_region].keys():
                                if type(omega_combo) is not tuple:
                                    continue

                                events = len(branch[cat][orf_region][omega_combo])
                                self.total_omegas[omega_combo]['nt_events'] = events
                                value_omegas_in_region =+ self.total_omegas[omega_combo]['value']*events

                            
                            branch[cat][orf_region]['nt_events'] = orf_region_events
                            branch[cat][orf_region]['value_omegas_in_region'] = value_omegas_in_region

```

Now, when we select the region, we use the sum of omega values on the region (`values_omega_in_region`) multiplied by the number of nucleotides with that combo, so the selection of the region looks something like this:

```python
orf_dict[orf_combo] = (all_maps[orf_combo]['len']/self.sequence.length) * orf_tree[orf_combo]['nt_events'] * orf_tree[orf_combo]['value_omegas_in_region']
 selected_orf_combo = self.weighted_random_choice(orf_dict, sum(orf_dict.values()))
```

The resulting Shannon entropy measure is more promising: 

![image](https://user-images.githubusercontent.com/42696510/192591767-fe54d796-4a40-43fc-abf7-d9ea30f4f90f.png)

@ArtPoon What do you think?

**Comment by horaciobam** [comment]
We were already doing this https://github.com/PoonLab/HexSE/issues/122#issuecomment-1259789855

**Comment by horaciobam** [comment]
Woho! Last commit 5f983212480f1a55e0a3a1cdde163b29414c97c3 worked :
![image](https://user-images.githubusercontent.com/42696510/193149105-33b35c90-5683-4cad-9e24-5af197f04dfd.png)

All genes have the same parameters:
```yaml
global_rate: 0.05
kappa: 0.3
mu: {classes: 1, dist: lognorm, shape: 1.0}
orfs:
  2308,3182;0,1625: {omega_classes: 2, omega_dist: gamma, omega_shape: 1.0}
  2849,3182;0,837: {omega_classes: 2, omega_dist: gamma, omega_shape: 1.0}
  1375,1840: {omega_classes: 2, omega_dist: gamma, omega_shape: 1.0}
  1815,2454: {omega_classes: 2, omega_dist: gamma, omega_shape: 1.0}
pi: {A: 0.25, C: 0.25, G: 0.25, T: 0.25}
```
