### ISSUE TITLE
Import errors when running run_simulation.py

### ISSUE THREAD

**Issue by SandeepThokala** [PoonLab/HexSE#127]
* Platform description: Windows 11, Python 3.10.7, HexSE 0.0.1
* Issues while running '.\hexse\run_simulation.py'
* Error message: `ImportError: attempted relative import with no known parent package`
* Fixed the import statements in run_simulation.py by making the following changes
<img src="https://user-images.githubusercontent.com/69971121/213340893-8bfbafc4-6285-4344-87c3-748e854062bb.png" width="600" height="auto">

*  Import error in '.\hexse\settings\__init__.py' while running '.\hexse\run_simulation.py'
*  Error message `ImportError: attempted relative import beyond top-level package`
*  Fixed the issue by making the following changes in '.\hexse\settings\__init__.py'
<img src="https://user-images.githubusercontent.com/69971121/213343523-e5c87174-496a-47b6-b237-863ab8318c74.png" width="425" height="auto">

**Comment by ArtPoon** [comment]
GitHub Markdown can recognize and highlight diff text:
```diff
- from .sequence_info
+ from sequence_info
```
